### ISSUE TITLE
Case Insensitive Synonyms

### ISSUE THREAD

**Issue by dashwav** [Mino-shiro/Minoshiro#1]
Right now if you add a synonym to the DB it will only check against the exact string match meaning that 

{Brushy Brushy} for example will parse, but {brushy brushy} won't be found, is this how we want to continue handling the synonyms or should we change it so the synonyms are case insensitive? @MaT1g3R

**Comment by MaT1g3R** [comment]
Yeah I think case insensitive is better

**Comment by dashwav** [comment]
Closing Issue
