### ISSUE TITLE
MAL replacement

### ISSUE THREAD

**Issue by dashwav** [Mino-shiro/Minoshiro#2]
Well since MAL doesn't look like it will be replacing itself anytime soon, I figure we should either deprecate or replace the MAL portion of the library.

[Jikan](https://jikan.docs.apiary.io/#) looks like it might be a decent replacement all things considered.

**Comment by dashwav** [comment]
Personally I would have no issues fully deprecating it since Jikan is a third party library and you can get most of the info needed from anilist, but that is probably my personal bias showing through

**Comment by MaT1g3R** [comment]
I'm in favor of fully deprecating MAL as well, since Anilist is just better
